linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - avoid_print
    - prefer_single_quotes
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - unnecessary_final
